### PR TITLE
Move to uniform.css and update bower deps

### PR DESCRIPTION
**Pull request by alshakero**
Fixes: https://github.com/Starcounter/HeadsOmni/issues/127

### CODE REVIEW

**Comment by mmnosek** [comment]
Thanks, @alshakero for good work, thanks @Mihaiii for the detailed explanation. I have an additional question - what do we need to make it look like our uniform docs? For instance, table on the screenshot above should (IMO) look like this: https://uniform.starcounter.io/UniformDocs/DataTable if we consider this app "adopted to the uniform". Do I miss something?

**Comment by alshakero** [comment]
You're right. Especially that there is pagination too. It would be way simpler to use uni-data-table. But it's mostly a C# change. not exactly my forte. Could you assign someone better?

If everyone is busy I can give it a shot for sure.

**Comment by Mihaiii** [comment]
Ok, I'm assigning myself for `uni-data-table` implementation.

**Comment by mmnosek** [comment]
How does this go @Mihaiii

**Comment by Mihaiii** [comment]
It's on my radar, haven't forgot about it.
I will address the issue, thank you for the reminder!

**Comment by Mihaiii** [comment]
Closing as it would have too many issues on merge.
Currently the lack of `uni-data-table` is not the only problem. I'll cover the whole app and this might take some time to do it right given that this app has many complex views.

Closed in favor of https://github.com/Starcounter/People/issues/181 .

**Pull request closed without merging**
